server:
  port: 7005
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/


spring:
  application:
    name: cloud-web
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
      org.springframework.security: debug
      com.cloud: debug