server:
  port: 8281
spring:
  application:
    name: dubbo-consumer

logging:
  level:
    com.dubbo: debug

dubbo:
  application:
    name: dubbo-cunsumer
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    timeout:
