server:
  port: 7003
  servlet:
    context-path: /sso
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/



spring:
  application:
    name: security-sso
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:7001/oauth/token
      user-authorization-uri: http://localhost:7001/oauth/authorize
      client-authentication-scheme: form
    resource:
      user-info-uri: http://localhost:7002/user
      prefer-token-info: false
logging:
  level:
      org.springframework.security: debug
