#服务器相关----------------------------------------------------------
server:
  port: 8080

#
spring:
  datasource:
    name: mysqldatasource
    url: jdbc:mysql://localhost:3306/lanmei?characterEncoding=utf-8
    username: root
    password: 563739007
   # type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  #thymeleaf模板配置-------------------------------------------------
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  #redis相关配置---------------------------------------------------
  redis:
    #host地址
    host: 127.0.0.1
    #端口
    port: 6379
    jedis:
      pool:
      #最大连接数 0表示无限制
        max-active: 8

    #密码
    #password: xxx
 # mvc:
 #   view:
    # 定位模板的目录
 #     prefix: / #classpath:/templates/
      # 给返回的页面添加后缀名
  #    suffix: .html
    #  filters: stat
    #  maxActive: 20
    #  initialSize: 1
    #  maxWait: 60000
    #  minIdle: 1
    #  timeBetweenEvictionRunsMillis: 60000
    #  minEvictableIdleTimeMillis: 300000
    #  validationQuery: select 'x'
    #  testWhileIdle: true
    #  testOnBorrow: false
   #   testOnReturn: false
   #   poolPreparedStatements: true
   #   maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: com.dao.mapper.*
swagger:
      basePackage: com.controller
      title: 猿医生のAPI
      description: 一生猿，一世猿。
      version: V1.0

