
spring:
  datasource:
    name: mysqldatasource
    url: jdbc:mysql://localhost:3306/javacode?characterEncoding=utf-8
    username: root
    password: 563739007
    driver-class-name: com.mysql.cj.jdbc.Driver
  mybatis:
    mapper-locations: com.springboot.transaction.mapper.*
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8119
logging:
  level:
    org.apache.ibatis: debug
    com:
      springboot:
        transaction:
          mapper: debug