server:
  port: 8483
spring:
  application:
    name: dubbo-provider1


logging:
  level:
    com.dubbo: debug
dubbo:
  application:
    name: dubbo-provider1
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
