server:
  port: 9002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

spring:
  application:
    name: cloud-security-server-client
security:
  oauth2:
    client:
      client-id: client_1
      client-secret: 123456
      access-token-uri: http://localhost:8009/oauth/token
      user-authorization-ur: http://localhost:8009/oauth/authorize
    resource:
      user-info-uri: http://localhost:8009/oauth/user

