server:
  port: 8283
spring:
  application:
    name: dubbo-provider
  dubbo:
    server: true
    registry: zookeeper://127.0.0.1:2181
    protocol:
      port: 20881

logging:
  level:
    com.dubbo: debug
dubbo:
  application:
    name: dubbo-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20880

