server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/


spring:
  application:
    name: oauth2-aserver
  #redis
  redis:
      #host地址
    host: 127.0.0.1
      #端口
    port: 6379
    jedis:
      pool:
          #最大连接数 0表示无限制
        max-active: 8
          #最大空闲处
        max-idle: 100
          #最大等待时间
        max-wait: 100
          #连接池中的最小空闲连接
        min-idle: 0
  #spring-thymeleaf模板配置-------------------------------------------------
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
      org.springframework.security: debug
      com.cloud: debug
# 忽略拦截
ignore:
  urls:
    - /auth/login
    - /auth/sumit
