server:
  port: 8008
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/


spring:
  application:
    name: security-provider
  boot:
    admin:
      client:
        url: "http://localhost:8006"
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"


